### PR TITLE
fix(label): text wrapping inside flexbox layout

### LINKED ISSUE #3834: FlexboxLayout doesn't measure and layout properly long labels
The following case fails on iPhone 6 and Nexus 5 emulator:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <FlexboxLayout flexDirection="row" alignItems="flex-start" verticalAlignment="top" backgroundColor="yellow">
        <Label text="txt" backgroundColor="#ffe4c4" class="date" width="80" flexShrink="0"></Label>
        <FlexboxLayout flexDirection="column" flexShrink="1" backgroundColor="#7fffd4">
            <Label text="There are many variations of passages of sssssss Lorem Ipsum available, but the majority have suffered alteration in some form!" textWrap="true" flexGrow="3"></Label>
            <Label text="Subtitle..." textWrap="true" fontSize="10"></Label>
        </FlexboxLayout>
    </FlexboxLayout>
</Page>
```
The ' some form!' string is absent or clipped.

> N.B. It looks like the first FB measures the second with some width, and then arranges the second with another smaller width, making the text in its Label wrap into an additional line, unforeseen during measure, wreaking havoc vertically in the the second FB layout.

### LINKED ISSUE #4834: Label in FlexboxLayout isn't sized correctly on iOS
Bit of a strange one.

```
<FlexboxLayout class="">
    <Image src="https://placehold.it/40x40" />
    <Label textWrap="true" text="a b c d e f g h i j k l m n o p q r s t u v w x" />
</FlexboxLayout>

<FlexboxLayout class="">
    <Image src="https://placehold.it/40x40" />
    <Label textWrap="true" text="a b c d e f g h i j k l m n o p q r s t u v w x y z 1" />
</FlexboxLayout>
```

The markup above produces this layout on iOS:

simulator-screen-shot-12-sep-2017 -17 42 11

As you can see the first Label is cut off after "v". Add a couple more characters to the string and the Label wraps properly and the full string is displayed.

This was in the iPhone 7 simulator. Other screen sizes will work/break with different string lengths.

I have a demo project here showing the issue: https://github.com/3rror404/ns-flexbox-issue

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

### PR DESCRIPTION
**Pull request by manoldonev**
(Widget part of) Fixes https://github.com/NativeScript/NativeScript/issues/4834
(Widget part of) Fixes https://github.com/NativeScript/NativeScript/issues/3834

NOTE: Also fixes iOS 11 specific scenarios with text wrapping outside flexbox.

### CODE REVIEW

File: android/widgets/src/main/java/org/nativescript/widgets/FlexboxLayout.java [hunk 1]
```diff
@@ -1071,9 +1071,24 @@ private int shrinkFlexItems(FlexLine flexLine, @FlexDirection int flexDirection,
...
-                            MeasureSpec.makeMeasureSpec(child.getMeasuredHeight(),
-                                    MeasureSpec.EXACTLY));
+
+                    int childWidthMeasureSpec = MeasureSpec.makeMeasureSpec(roundedCalculatedWidth, MeasureSpec.EXACTLY);
+
+                    // NOTE: for controls that support internal content wrapping (e.g. TextView) reducing the width
+                    // might result in increased height e.g. text that could be shown on one line for larger
+                    // width needs to be wrapped in two when width is reduced.
+                    // As a result we cannot unconditionally measure with EXACTLY the current measured height
+                    int childHeightMeasureSpec = getChildMeasureSpec(this.getMeasuredHeightAndState(),
```
Comment (manoldonev) [inline android/widgets/src/main/java/org/nativescript/widgets/FlexboxLayout.java:1081]: Basically this is the Android version of the fix from this PR https://github.com/NativeScript/NativeScript/pull/5781

**Review by ADjenkov — APPROVED** [review]
